name: Sync Fork

on:
  schedule:
    - cron: '*/2 * * * *'  # Runs every 2 minutes
  workflow_dispatch:     # Allows manual triggering

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          repository: bia-pain-bache/BPB-Worker-Panel
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Sync Fork
        run: |
          git remote add fork https://github.com/mamcloud/BPB-Worker-Panel.git
          git push fork main --force
